---
title: "Final Project: Add title here"
format: pdf
editor: source
editor_options: 
  chunk_output_type: console
---




<!--  

This is a template for creating your final project write-up. It lays out the
sections that should be in your write-up and describes a little about these
sections. Your write-up should be between 5-8 pages long and should contain:

    1. Introduction: 
      - What question you are addressing?
      - Why is the question important? 
      - Where did you get the data from? 
    
    2. Plots of the data
      - One or more plots.
    
    3. Hypothesis tests: 
      - Go through all 5 steps of a randomization test. 
      - Also run a parametric test.
    
    4. Confidence intervals: 
      - Calculate using the bootstrap
      - Also calculate a confidence interval using a parametric method. 
    
    5. Conclusions: 
      - What did you find?
      - Future directions.
      - Anything else you want to discuss.
    
    6. Reflection: 
      - What went well?
      - What did you struggle with?
      - What analyses did you do that you are not including?
      - Anything else you want to mention about the learning process, etc.
      - Also fill out the final project reflection on Canvas.

    7. Appendix (optional): 
      - If there is additional code you would like to include you can create an 
          appendix that has this code (this will help ensure your project is within
          the 8 page limit). 
      - Having this section is not necessary however.


Make sure that your write-up looks good! Using additional Quarto features can
help with this, and so some useful websites are:

1)  https://www.rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf
2)  https://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf


--> 






<!-- There are some options that will make your document look better  -->
```{r message=FALSE, warning=FALSE, tidy=TRUE, echo=FALSE}

library(SDS1000)    
library(knitr)


# makes sure the code is wrapped to fit when it creates a pdf
opts_chunk$set(tidy.opts=list(width.cutoff=60))   
   
# set the random number generator to always give the same sequence of random numbers
set.seed(1)  
    

```








$\\$






## Introduction 


<!--  

Write ~1-3 paragraphs describing:

1. What problem you are addressing and why the problem you are addressing is
interesting?

2. Where did you get the data from? Include a link to the website where you got
the data if applicable.

3. What other analyses have already been done with the data? Include links to
other analyses.

--> 





   
$\\$   
   
    





## Results




$\\$
    




### Plot the data: Change the subtitle here to describe what you are plotting


<!--  

Create one or more plots of your data. Describe the plot(s), what they show, and
why they are of interest to your question. Include the code to create these
plots in the R chunk below. You can also discuss the plots after the code
section.

--> 




```{r message=FALSE, warning=FALSE, tidy=TRUE}






```





<!--  

Possible additional discussion of the plots here. 

--> 








$\\$    
    







    

### Hypothesis tests: Change this sub-title to describe what the tests consist of

<!--  

Run a hypothesis tests on your data using computational randomization methods,
as well as parametric methods. For the randomization methods, please be sure to
complete all 5 steps of the 5 step procedure discussed in class, and include
your code in the R chunk below. For the parametric test, make sure that you get
the same result (i.e., a similar p-value) or if you don't, explain why you think
these types of tests differ.

--> 




```{r message=FALSE, warning=FALSE, tidy=TRUE}




```


<!--  

Possible additional discussion of the 5-step procedure and hypothesis tests here. 

--> 








$\\$      
    
    
    
    
    
    
    
    

### Confidence intervals: Change this sub-title to describe the confidence intervals you are creating

<!--  

Calculate a confidence interval using the bootstrap and parametric methods.
Describe what the confidence interval tell you about your question of interest,
and include your code in the R chunk below.

--> 



```{r message=FALSE, warning=FALSE, tidy=TRUE}




```


<!--  

Possible additional discussion of the confidence intervals here. 

--> 









$\\$


    
    
    
    
    
    


## Conclusion 



<!--  

1-3 paragraphs summarizing what you found, how the findings address your
question of interest, and possible future directions.

-->










$\\$







## Reflection  



<!--  


Write 1-3 paragraphs describing what went well with this project and what was
more difficult. Also describe any additional things you tried that you did not
end up including in this write-up, and approximately how much time you spend
working the project.

Finally, please go to Canvas fill out the Final Project Reflection to let us
know how this project (and the class overall) went.



-->





$\\$







## Appendix


<!--  


You can include additional code here if you could not fit it into the body of
the document. Make sure your code is well commented and easy read.

This section is optional, so it is fine if you do not include this section as well. 

-->





